### PR TITLE
Disable unused-parameter golangci check

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This rule has been causing a lot of issues throughout the plugin repos. Disabling it here to avoid this

### CODE REVIEW

**Comment by mickmister** [comment]
@hanzei Any ideas why lint is still failing with this change? I used this as a reference https://golangci-lint.run/usage/configuration

**Comment by hanzei** [comment]
`unused-parameter` is not it's own linter. It's a sub-linter of `revive`. You need to do something like https://github.com/mattermost/mattermost/blob/5f8133254de425d92cc80092972a4ace40792639/server/.golangci.yml#L43-L46

**Comment by mickmister** [comment]
@hanzei Looks like it's fixed 🚀  Thank you!

**Review by hanzei — CHANGES_REQUESTED** [review]
Do we need the `path` specification?  Is it possible to apply the rule to all files?

**Review by hanzei — APPROVED** [review]

**Pull request merged**
